version: '2.15.1'
services:
  api:
    build: ./requirements/node-test
    container_name: api_c
    ports:
      - '6969:4000'
    # volumes:
    #   - relPath:relPath
    env_file:
      - .env
    networks:
      - network
    restart: always
