version: '3'

networks:
  inception_network:
    name: inception_network

volumes:
  inception_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wp

services:
  nginx:
    container_name: "nginx"
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    ports:
      - "8080:80"
    networks:
      - inception_network
    volumes:
      - inception_volume:/app
    restart: unless-stopped


  wordpress:
    container_name: "wordpress"
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    env_file: .env
    networks:
      - inception_network
    volumes:
      - inception_volume:/app
    restart: unless-stopped
  
  mariadb:
    container_name: "mariadb"
    build:
      context: ./requirements/mariadb
    env_file: .env
    networks:
      - inception_network
    restart: unless-stopped