version: '3'

networks:
  inception_network:
    name: inception_network

services:
  nginx:
    container_name: "inception_nginx"
    build:
      context: ./requirements/nginx
    ports:
      - "8080:80"
    networks:
      - inception_network

  wordpress:
    container_name: "inception_wordpress"
    build:
      context: ./requirements/wordpress
    networks:
      - inception_network