version: '3'

# ============================================================================ #

services:

  nginx:
    container_name: "nginx"
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    ports:
      - "4000:4000"
    networks:
      - inception_network
    volumes:
      - volume_wordpress:/app
    restart: always

  wordpress:
    container_name: "wordpress"
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    env_file: .env
    networks:
      - inception_network
    volumes:
      - volume_wordpress:/app
    restart: always
  
  mariadb:
    container_name: "mariadb"
    build:
      context: ./requirements/mariadb
    env_file: .env
    networks:
      - inception_network
    volumes:
      - volume_mariadb:/var/lib/mysql
    restart: always

# ============================================================================ #

networks:
  inception_network:
    name: inception_network

# ============================================================================ #

volumes:

  volume_wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wp
  
  volume_mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/db