version: '3'
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx-container
    ports:
      - '8000:80'
    # env_file:
    #   - .env
    # networks:
    #   - network
    restart: always
