version: '3'

networks:
  inception_network:
    name: inception_network

volumes:
  inception_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$HOME/data'



services:
  nginx:
    container_name: "inception_nginx"
    build:
      context: ./requirements/nginx
    ports:
      - "8080:80"
    networks:
      - inception_network

  wordpress:
    container_name: "inception_wordpress"
    build:
      context: ./requirements/wordpress
    env_file: .env
    networks:
      - inception_network
    volumes:
      - inception_volume:/app