version: '3'
services:
  # nginx:
  #   container_name: "inception_nginx"
  #   build:
  #     context: ./requirements/nginx
  #   ports:
  #     - "8080:80"
  wordpress:
    container_name: "inception_wordpress"
    build:
      context: ./requirements/wordpress
    ports:
      - "8080:80"