DROP DATABASE IF EXISTS test;
CREATE DATABASE IF NOT EXISTS SQL_DATABASE DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE USER IF NOT EXISTS 'SQL_USER'@'localhost' IDENTIFIED BY 'SQL_PASSWORD';
GRANT ALL PRIVILEGES ON SQL_DATABASE.* TO 'SQL_USER'@'%' IDENTIFIED BY 'SQL_PASSWORD';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'SQL_USER';